
package views;

import controllers.CalculadoraController;
import java.awt.Toolkit;
import models.CalculadoraModel;

public class PanelCalculadora extends javax.swing.JFrame {
    
    public PanelCalculadora() {
        initComponents();
        setLocationRelativeTo(null);
        CalculadoraModel model = new CalculadoraModel();
        CalculadoraController controller = new CalculadoraController(this, model);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jLabelOperacion = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        btnDividir = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        btnCambiarModo = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOperacion.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabelOperacion.setForeground(new java.awt.Color(3, 3, 3));
        jLabelOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelBackground.add(jLabelOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, 40));

        jLabelResultado.setFont(new java.awt.Font("Open Sans", 1, 48)); // NOI18N
        jLabelResultado.setForeground(new java.awt.Color(3, 3, 3));
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelBackground.add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 70));

        btnDividir.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        btnDividir.setForeground(new java.awt.Color(255, 254, 248));
        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2.png"))); // NOI18N
        btnDividir.setText("/");
        btnDividir.setBorderPainted(false);
        btnDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDividir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2-selected.png"))); // NOI18N
        jPanelBackground.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 50, 50));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-min.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBackground.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        btnBorrar.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 254, 248));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-borrar.png"))); // NOI18N
        btnBorrar.setBorderPainted(false);
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-borrar-selected.png"))); // NOI18N
        jPanelBackground.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 50, 50));

        btn7.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(26, 26, 26));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn7.setText("7");
        btn7.setBorderPainted(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 50));

        btn8.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(26, 26, 26));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn8.setText("8");
        btn8.setBorderPainted(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, 50));

        btn9.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(26, 26, 26));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn9.setText("9");
        btn9.setBorderPainted(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, 50));

        btnMultiplicar.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        btnMultiplicar.setForeground(new java.awt.Color(255, 254, 248));
        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2.png"))); // NOI18N
        btnMultiplicar.setText("*");
        btnMultiplicar.setBorderPainted(false);
        btnMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMultiplicar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2-selected.png"))); // NOI18N
        jPanelBackground.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 50, 50));

        btn4.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(26, 26, 26));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn4.setText("4");
        btn4.setBorderPainted(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 50, 50));

        btn5.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(26, 26, 26));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn5.setText("5");
        btn5.setBorderPainted(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 50, 50));

        btn6.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(26, 26, 26));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn6.setText("6");
        btn6.setBorderPainted(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 50, 50));

        btnSumar.setFont(new java.awt.Font("Open Sans", 1, 27)); // NOI18N
        btnSumar.setForeground(new java.awt.Color(255, 254, 248));
        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2.png"))); // NOI18N
        btnSumar.setText("+");
        btnSumar.setBorderPainted(false);
        btnSumar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSumar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2-selected.png"))); // NOI18N
        jPanelBackground.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 50, 50));

        btn1.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(26, 26, 26));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn1.setText("1");
        btn1.setBorderPainted(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 50));

        btn2.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(26, 26, 26));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn2.setText("2");
        btn2.setBorderPainted(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 50, 50));

        btn3.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(26, 26, 26));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btn3.setText("3");
        btn3.setBorderPainted(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 50, 50));

        btnRestar.setFont(new java.awt.Font("Open Sans", 1, 27)); // NOI18N
        btnRestar.setForeground(new java.awt.Color(255, 254, 248));
        btnRestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2.png"))); // NOI18N
        btnRestar.setText("-");
        btnRestar.setBorderPainted(false);
        btnRestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRestar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2-selected.png"))); // NOI18N
        jPanelBackground.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 50, 50));

        btn0.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(26, 26, 26));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.png"))); // NOI18N
        btn0.setText("0");
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4-selected.png"))); // NOI18N
        jPanelBackground.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, 50));

        btnComa.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btnComa.setForeground(new java.awt.Color(26, 26, 26));
        btnComa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3.png"))); // NOI18N
        btnComa.setText(",");
        btnComa.setBorderPainted(false);
        btnComa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn3-selected.png"))); // NOI18N
        jPanelBackground.add(btnComa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 50, 50));

        btnIgual.setFont(new java.awt.Font("Open Sans", 1, 27)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 254, 248));
        btnIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2.png"))); // NOI18N
        btnIgual.setText("=");
        btnIgual.setBorderPainted(false);
        btnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2-selected.png"))); // NOI18N
        jPanelBackground.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 50, 50));

        btnBorrarTodo.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        btnBorrarTodo.setForeground(new java.awt.Color(255, 254, 248));
        btnBorrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnBorrarTodo.setText("C");
        btnBorrarTodo.setBorderPainted(false);
        btnBorrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarTodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarTodo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-selected.png"))); // NOI18N
        jPanelBackground.add(btnBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 50));

        btnCambiarModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-modeLight.png"))); // NOI18N
        btnCambiarModo.setBorderPainted(false);
        btnCambiarModo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBackground.add(btnCambiarModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 145, 50, 25));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-close.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBackground.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn0;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnBorrarTodo;
    public javax.swing.JButton btnCambiarModo;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnComa;
    public javax.swing.JButton btnDividir;
    public javax.swing.JButton btnIgual;
    public javax.swing.JButton btnMinimizar;
    public javax.swing.JButton btnMultiplicar;
    public javax.swing.JButton btnRestar;
    public javax.swing.JButton btnSumar;
    public javax.swing.JLabel jLabelOperacion;
    public javax.swing.JLabel jLabelResultado;
    public javax.swing.JPanel jPanelBackground;
    // End of variables declaration//GEN-END:variables
}
